// A small, typed list of countries with dialing codes and emoji flags.
// This can be used to populate the `.country-select` in the contact form.

export interface CountryCode {
	name: string;    // human readable name
	iso: string;     // ISO 3166-1 alpha-2
	flag: string;    // emoji flag
	dial_code: string; // dialing code including leading +
}

export const countryCodes: CountryCode[] = [
	{ name: 'Afghanistan', iso: 'AF', flag: '🇦🇫', dial_code: '+93' },
	{ name: 'Albania', iso: 'AL', flag: '🇦🇱', dial_code: '+355' },
	{ name: 'Algeria', iso: 'DZ', flag: '🇩🇿', dial_code: '+213' },
	{ name: 'Andorra', iso: 'AD', flag: '🇦🇩', dial_code: '+376' },
	{ name: 'Angola', iso: 'AO', flag: '🇦🇴', dial_code: '+244' },
	{ name: 'Antigua and Barbuda', iso: 'AG', flag: '🇦🇬', dial_code: '+1-268' },
	{ name: 'Argentina', iso: 'AR', flag: '🇦🇷', dial_code: '+54' },
	{ name: 'Armenia', iso: 'AM', flag: '🇦🇲', dial_code: '+374' },
	{ name: 'Aruba', iso: 'AW', flag: '🇦🇼', dial_code: '+297' },
	{ name: 'Australia', iso: 'AU', flag: '🇦🇺', dial_code: '+61' },
	{ name: 'Austria', iso: 'AT', flag: '🇦🇹', dial_code: '+43' },
	{ name: 'Azerbaijan', iso: 'AZ', flag: '🇦🇿', dial_code: '+994' },
	{ name: 'Bahamas', iso: 'BS', flag: '�🇸', dial_code: '+1-242' },
	{ name: 'Bahrain', iso: 'BH', flag: '🇧🇭', dial_code: '+973' },
	{ name: 'Bangladesh', iso: 'BD', flag: '🇧🇩', dial_code: '+880' },
	{ name: 'Barbados', iso: 'BB', flag: '🇧🇧', dial_code: '+1-246' },
	{ name: 'Belarus', iso: 'BY', flag: '🇧🇾', dial_code: '+375' },
	{ name: 'Belgium', iso: 'BE', flag: '🇧🇪', dial_code: '+32' },
	{ name: 'Belize', iso: 'BZ', flag: '🇧🇿', dial_code: '+501' },
	{ name: 'Benin', iso: 'BJ', flag: '🇧🇯', dial_code: '+229' },
	{ name: 'Bhutan', iso: 'BT', flag: '🇧🇹', dial_code: '+975' },
	{ name: 'Bolivia', iso: 'BO', flag: '🇧🇴', dial_code: '+591' },
	{ name: 'Bosnia and Herzegovina', iso: 'BA', flag: '🇧🇦', dial_code: '+387' },
	{ name: 'Botswana', iso: 'BW', flag: '🇧🇼', dial_code: '+267' },
	{ name: 'Brazil', iso: 'BR', flag: '🇧🇷', dial_code: '+55' },
	{ name: 'Brunei', iso: 'BN', flag: '�🇳', dial_code: '+673' },
	{ name: 'Bulgaria', iso: 'BG', flag: '🇧�🇬', dial_code: '+359' },
	{ name: 'Burkina Faso', iso: 'BF', flag: '🇧🇫', dial_code: '+226' },
	{ name: 'Burundi', iso: 'BI', flag: '🇧🇮', dial_code: '+257' },
	{ name: 'Cabo Verde', iso: 'CV', flag: '🇨🇻', dial_code: '+238' },
	{ name: 'Cambodia', iso: 'KH', flag: '��', dial_code: '+855' },
	{ name: 'Cameroon', iso: 'CM', flag: '🇨🇲', dial_code: '+237' },
	{ name: 'Canada', iso: 'CA', flag: '🇨🇦', dial_code: '+1' },
	{ name: 'Central African Republic', iso: 'CF', flag: '🇨🇫', dial_code: '+236' },
	{ name: 'Chad', iso: 'TD', flag: '🇹🇩', dial_code: '+235' },
	{ name: 'Chile', iso: 'CL', flag: '🇨🇱', dial_code: '+56' },
	{ name: 'China', iso: 'CN', flag: '🇨🇳', dial_code: '+86' },
	{ name: 'Colombia', iso: 'CO', flag: '🇨🇴', dial_code: '+57' },
	{ name: 'Comoros', iso: 'KM', flag: '🇰🇲', dial_code: '+269' },
	{ name: 'Congo (Brazzaville)', iso: 'CG', flag: '🇨🇬', dial_code: '+242' },
	{ name: 'Congo (Kinshasa)', iso: 'CD', flag: '🇨🇩', dial_code: '+243' },
	{ name: 'Costa Rica', iso: 'CR', flag: '🇨🇷', dial_code: '+506' },
	{ name: "Côte d'Ivoire", iso: 'CI', flag: '🇨🇮', dial_code: '+225' },
	{ name: 'Croatia', iso: 'HR', flag: '🇭🇷', dial_code: '+385' },
	{ name: 'Cuba', iso: 'CU', flag: '�🇺', dial_code: '+53' },
	{ name: 'Curaçao', iso: 'CW', flag: '🇨🇼', dial_code: '+599' },
	{ name: 'Cyprus', iso: 'CY', flag: '🇨🇾', dial_code: '+357' },
	{ name: 'Czechia', iso: 'CZ', flag: '🇨🇿', dial_code: '+420' },
	{ name: 'Denmark', iso: 'DK', flag: '🇩🇰', dial_code: '+45' },
	{ name: 'Djibouti', iso: 'DJ', flag: '🇩🇯', dial_code: '+253' },
	{ name: 'Dominica', iso: 'DM', flag: '🇩🇲', dial_code: '+1-767' },
	{ name: 'Dominican Republic', iso: 'DO', flag: '🇩🇴', dial_code: '+1-809' },
	{ name: 'Ecuador', iso: 'EC', flag: '🇪🇨', dial_code: '+593' },
	{ name: 'Egypt', iso: 'EG', flag: '🇪🇬', dial_code: '+20' },
	{ name: 'El Salvador', iso: 'SV', flag: '🇸🇻', dial_code: '+503' },
	{ name: 'Equatorial Guinea', iso: 'GQ', flag: '🇬🇶', dial_code: '+240' },
	{ name: 'Eritrea', iso: 'ER', flag: '��', dial_code: '+291' },
	{ name: 'Estonia', iso: 'EE', flag: '�🇪🇪', dial_code: '+372' },
	{ name: 'Eswatini', iso: 'SZ', flag: '🇸🇿', dial_code: '+268' },
	{ name: 'Ethiopia', iso: 'ET', flag: '🇪🇹', dial_code: '+251' },
	{ name: 'Fiji', iso: 'FJ', flag: '🇫🇯', dial_code: '+679' },
	{ name: 'Finland', iso: 'FI', flag: '🇫🇮', dial_code: '+358' },
	{ name: 'France', iso: 'FR', flag: '🇫🇷', dial_code: '+33' },
	{ name: 'Gabon', iso: 'GA', flag: '🇬🇦', dial_code: '+241' },
	{ name: 'Gambia', iso: 'GM', flag: '🇬🇲', dial_code: '+220' },
	{ name: 'Georgia', iso: 'GE', flag: '🇬🇪', dial_code: '+995' },
	{ name: 'Germany', iso: 'DE', flag: '🇩🇪', dial_code: '+49' },
	{ name: 'Ghana', iso: 'GH', flag: '🇬🇭', dial_code: '+233' },
	{ name: 'Greece', iso: 'GR', flag: '🇬🇷', dial_code: '+30' },
	{ name: 'Grenada', iso: 'GD', flag: '🇬🇩', dial_code: '+1-473' },
	{ name: 'Guatemala', iso: 'GT', flag: '🇬🇹', dial_code: '+502' },
	{ name: 'Guinea', iso: 'GN', flag: '🇬🇳', dial_code: '+224' },
	{ name: 'Guinea-Bissau', iso: 'GW', flag: '🇬🇼', dial_code: '+245' },
	{ name: 'Guyana', iso: 'GY', flag: '🇬🇾', dial_code: '+592' },
	{ name: 'Haiti', iso: 'HT', flag: '🇭🇹', dial_code: '+509' },
	{ name: 'Honduras', iso: 'HN', flag: '🇭🇳', dial_code: '+504' },
	{ name: 'Hungary', iso: 'HU', flag: '🇭🇺', dial_code: '+36' },
	{ name: 'Iceland', iso: 'IS', flag: '�🇸', dial_code: '+354' },
	{ name: 'India', iso: 'IN', flag: '🇮🇳', dial_code: '+91' },
	{ name: 'Indonesia', iso: 'ID', flag: '🇮🇩', dial_code: '+62' },
	{ name: 'Iran', iso: 'IR', flag: '🇮🇷', dial_code: '+98' },
	{ name: 'Iraq', iso: 'IQ', flag: '🇮🇶', dial_code: '+964' },
	{ name: 'Ireland', iso: 'IE', flag: '🇮🇪', dial_code: '+353' },
	{ name: 'Israel', iso: 'IL', flag: '🇮🇱', dial_code: '+972' },
	{ name: 'Italy', iso: 'IT', flag: '🇮🇹', dial_code: '+39' },
	{ name: 'Jamaica', iso: 'JM', flag: '🇯🇲', dial_code: '+1-876' },
	{ name: 'Japan', iso: 'JP', flag: '🇯🇵', dial_code: '+81' },
	{ name: 'Jordan', iso: 'JO', flag: '🇯🇴', dial_code: '+962' },
	{ name: 'Kazakhstan', iso: 'KZ', flag: '🇰🇿', dial_code: '+7' },
	{ name: 'Kenya', iso: 'KE', flag: '🇰🇪', dial_code: '+254' },
	{ name: 'Kiribati', iso: 'KI', flag: '🇰🇮', dial_code: '+686' },
	{ name: 'Kuwait', iso: 'KW', flag: '🇰🇼', dial_code: '+965' },
	{ name: 'Kyrgyzstan', iso: 'KG', flag: '🇰🇬', dial_code: '+996' },
	{ name: 'Laos', iso: 'LA', flag: '🇱🇦', dial_code: '+856' },
	{ name: 'Latvia', iso: 'LV', flag: '🇱🇻', dial_code: '+371' },
	{ name: 'Lebanon', iso: 'LB', flag: '🇱🇧', dial_code: '+961' },
	{ name: 'Lesotho', iso: 'LS', flag: '🇱🇸', dial_code: '+266' },
	{ name: 'Liberia', iso: 'LR', flag: '�🇷', dial_code: '+231' },
	{ name: 'Libya', iso: 'LY', flag: '🇱🇾', dial_code: '+218' },
	{ name: 'Liechtenstein', iso: 'LI', flag: '🇱🇮', dial_code: '+423' },
	{ name: 'Lithuania', iso: 'LT', flag: '🇱🇹', dial_code: '+370' },
	{ name: 'Luxembourg', iso: 'LU', flag: '🇱🇺', dial_code: '+352' },
	{ name: 'Madagascar', iso: 'MG', flag: '🇲🇬', dial_code: '+261' },
	{ name: 'Malawi', iso: 'MW', flag: '🇲🇼', dial_code: '+265' },
	{ name: 'Malaysia', iso: 'MY', flag: '🇲🇾', dial_code: '+60' },
	{ name: 'Maldives', iso: 'MV', flag: '🇲🇻', dial_code: '+960' },
	{ name: 'Mali', iso: 'ML', flag: '🇲🇱', dial_code: '+223' },
	{ name: 'Malta', iso: 'MT', flag: '🇲🇹', dial_code: '+356' },
	{ name: 'Marshall Islands', iso: 'MH', flag: '🇲🇭', dial_code: '+692' },
	{ name: 'Mauritania', iso: 'MR', flag: '🇲🇷', dial_code: '+222' },
	{ name: 'Mauritius', iso: 'MU', flag: '🇲🇺', dial_code: '+230' },
	{ name: 'Mexico', iso: 'MX', flag: '🇲🇽', dial_code: '+52' },
	{ name: 'Micronesia', iso: 'FM', flag: '🇫🇲', dial_code: '+691' },
	{ name: 'Moldova', iso: 'MD', flag: '🇲🇩', dial_code: '+373' },
	{ name: 'Monaco', iso: 'MC', flag: '🇲🇨', dial_code: '+377' },
	{ name: 'Mongolia', iso: 'MN', flag: '🇲🇳', dial_code: '+976' },
	{ name: 'Montenegro', iso: 'ME', flag: '🇲🇪', dial_code: '+382' },
	{ name: 'Morocco', iso: 'MA', flag: '🇲🇦', dial_code: '+212' },
	{ name: 'Mozambique', iso: 'MZ', flag: '🇲🇿', dial_code: '+258' },
	{ name: 'Myanmar', iso: 'MM', flag: '🇲🇲', dial_code: '+95' },
	{ name: 'Namibia', iso: 'NA', flag: '🇳🇦', dial_code: '+264' },
	{ name: 'Nauru', iso: 'NR', flag: '🇳🇷', dial_code: '+674' },
	{ name: 'Nepal', iso: 'NP', flag: '🇳🇵', dial_code: '+977' },
	{ name: 'Netherlands', iso: 'NL', flag: '🇳🇱', dial_code: '+31' },
	{ name: 'New Zealand', iso: 'NZ', flag: '🇳🇿', dial_code: '+64' },
	{ name: 'Nicaragua', iso: 'NI', flag: '🇳🇮', dial_code: '+505' },
	{ name: 'Niger', iso: 'NE', flag: '🇳🇪', dial_code: '+227' },
	{ name: 'Nigeria', iso: 'NG', flag: '🇳🇬', dial_code: '+234' },
	{ name: 'North Korea', iso: 'KP', flag: '🇰🇵', dial_code: '+850' },
	{ name: 'North Macedonia', iso: 'MK', flag: '�🇰', dial_code: '+389' },
	{ name: 'Norway', iso: 'NO', flag: '🇳🇴', dial_code: '+47' },
	{ name: 'Oman', iso: 'OM', flag: '🇴🇲', dial_code: '+968' },
	{ name: 'Pakistan', iso: 'PK', flag: '🇵🇰', dial_code: '+92' },
	{ name: 'Palau', iso: 'PW', flag: '🇵🇼', dial_code: '+680' },
	{ name: 'Panama', iso: 'PA', flag: '🇵🇦', dial_code: '+507' },
	{ name: 'Papua New Guinea', iso: 'PG', flag: '🇵🇬', dial_code: '+675' },
	{ name: 'Paraguay', iso: 'PY', flag: '🇵🇾', dial_code: '+595' },
	{ name: 'Peru', iso: 'PE', flag: '🇵🇪', dial_code: '+51' },
	{ name: 'Philippines', iso: 'PH', flag: '�🇭', dial_code: '+63' },
	{ name: 'Poland', iso: 'PL', flag: '🇵🇱', dial_code: '+48' },
	{ name: 'Portugal', iso: 'PT', flag: '�🇹', dial_code: '+351' },
	{ name: 'Qatar', iso: 'QA', flag: '🇶🇦', dial_code: '+974' },
	{ name: 'Romania', iso: 'RO', flag: '🇷🇴', dial_code: '+40' },
	{ name: 'Russia', iso: 'RU', flag: '🇷🇺', dial_code: '+7' },
	{ name: 'Rwanda', iso: 'RW', flag: '🇷🇼', dial_code: '+250' },
	{ name: 'Saint Kitts and Nevis', iso: 'KN', flag: '🇰🇳', dial_code: '+1-869' },
	{ name: 'Saint Lucia', iso: 'LC', flag: '🇱🇨', dial_code: '+1-758' },
	{ name: 'Saint Vincent and the Grenadines', iso: 'VC', flag: '🇻🇨', dial_code: '+1-784' },
	{ name: 'Samoa', iso: 'WS', flag: '🇼🇸', dial_code: '+685' },
	{ name: 'San Marino', iso: 'SM', flag: '🇸🇲', dial_code: '+378' },
	{ name: 'Sao Tome and Principe', iso: 'ST', flag: '🇸🇹', dial_code: '+239' },
	{ name: 'Saudi Arabia', iso: 'SA', flag: '🇸🇦', dial_code: '+966' },
	{ name: 'Senegal', iso: 'SN', flag: '🇸🇳', dial_code: '+221' },
	{ name: 'Serbia', iso: 'RS', flag: '🇷🇸', dial_code: '+381' },
	{ name: 'Seychelles', iso: 'SC', flag: '🇸🇨', dial_code: '+248' },
	{ name: 'Sierra Leone', iso: 'SL', flag: '�🇱', dial_code: '+232' },
	{ name: 'Singapore', iso: 'SG', flag: '🇸🇬', dial_code: '+65' },
	{ name: 'Slovakia', iso: 'SK', flag: '🇸🇰', dial_code: '+421' },
	{ name: 'Slovenia', iso: 'SI', flag: '🇸🇮', dial_code: '+386' },
	{ name: 'Solomon Islands', iso: 'SB', flag: '🇸�', dial_code: '+677' },
	{ name: 'Somalia', iso: 'SO', flag: '🇸🇴', dial_code: '+252' },
	{ name: 'South Africa', iso: 'ZA', flag: '🇿🇦', dial_code: '+27' },
	{ name: 'South Korea', iso: 'KR', flag: '🇰🇷', dial_code: '+82' },
	{ name: 'South Sudan', iso: 'SS', flag: '🇸🇸', dial_code: '+211' },
	{ name: 'Spain', iso: 'ES', flag: '🇪🇸', dial_code: '+34' },
	{ name: 'Sri Lanka', iso: 'LK', flag: '🇱🇰', dial_code: '+94' },
	{ name: 'Sudan', iso: 'SD', flag: '🇸🇩', dial_code: '+249' },
	{ name: 'Suriname', iso: 'SR', flag: '🇸🇷', dial_code: '+597' },
	{ name: 'Sweden', iso: 'SE', flag: '🇸🇪', dial_code: '+46' },
	{ name: 'Switzerland', iso: 'CH', flag: '🇨🇭', dial_code: '+41' },
	{ name: 'Syria', iso: 'SY', flag: '🇸🇾', dial_code: '+963' },
	{ name: 'Taiwan', iso: 'TW', flag: '🇹🇼', dial_code: '+886' },
	{ name: 'Tajikistan', iso: 'TJ', flag: '🇹🇯', dial_code: '+992' },
	{ name: 'Tanzania', iso: 'TZ', flag: '🇹🇿', dial_code: '+255' },
	{ name: 'Thailand', iso: 'TH', flag: '🇹🇭', dial_code: '+66' },
	{ name: 'Timor-Leste', iso: 'TL', flag: '🇹🇱', dial_code: '+670' },
	{ name: 'Togo', iso: 'TG', flag: '🇹🇬', dial_code: '+228' },
	{ name: 'Tonga', iso: 'TO', flag: '🇹🇴', dial_code: '+676' },
	{ name: 'Trinidad and Tobago', iso: 'TT', flag: '🇹🇹', dial_code: '+1-868' },
	{ name: 'Tunisia', iso: 'TN', flag: '��🇳', dial_code: '+216' },
	{ name: 'Turkey', iso: 'TR', flag: '�🇷', dial_code: '+90' },
	{ name: 'Turkmenistan', iso: 'TM', flag: '🇹🇲', dial_code: '+993' },
	{ name: 'Tuvalu', iso: 'TV', flag: '🇹🇻', dial_code: '+688' },
	{ name: 'Uganda', iso: 'UG', flag: '🇺🇬', dial_code: '+256' },
	{ name: 'Ukraine', iso: 'UA', flag: '🇺🇦', dial_code: '+380' },
	{ name: 'United Arab Emirates', iso: 'AE', flag: '🇦🇪', dial_code: '+971' },
	{ name: 'United Kingdom', iso: 'GB', flag: '🇬🇧', dial_code: '+44' },
	{ name: 'United States', iso: 'US', flag: '🇺🇸', dial_code: '+1' },
	{ name: 'Uruguay', iso: 'UY', flag: '🇺🇾', dial_code: '+598' },
	{ name: 'Uzbekistan', iso: 'UZ', flag: '🇺🇿', dial_code: '+998' },
	{ name: 'Vanuatu', iso: 'VU', flag: '🇻🇺', dial_code: '+678' },
	{ name: 'Vatican City', iso: 'VA', flag: '🇻🇦', dial_code: '+379' },
	{ name: 'Venezuela', iso: 'VE', flag: '🇻�', dial_code: '+58' },
	{ name: 'Vietnam', iso: 'VN', flag: '🇻🇳', dial_code: '+84' },
	{ name: 'Yemen', iso: 'YE', flag: '🇾🇪', dial_code: '+967' },
	{ name: 'Zambia', iso: 'ZM', flag: '🇿🇲', dial_code: '+260' },
	{ name: 'Zimbabwe', iso: 'ZW', flag: '🇿🇼', dial_code: '+263' }
];

export default countryCodes;
